return {
	Police = {
		teamName = "Police",
		basePay = 250,
		jobDescription = "Maintain law and order in the city.",
	},
	FireService = {
		teamName = "Fire Service",
		basePay = 230,
		jobDescription = "Respond to fire emergencies and rescue civilians.",
	},
	Paramedic = {
		teamName = "Paramedic",
		basePay = 220,
		jobDescription = "Provide medical assistance and transport to those in need.",
	},
	Civilian = {
		teamName = "Civilian",
		basePay = 50,
		jobDescription = "Live your life as a regular citizen.",
	},
}